### ISSUE TITLE
Documentation not up-to-date for manual installation

### ISSUE THREAD

**Issue by qwertfisch** [nebulade/meemo#108]
The documentation on manual installation is not correct. The mentioned environment variables are wrong, as most of them are now prefixed with _CLOUDRON\__. The necessary variables are
- CLOUDRON_APP_ORIGIN
- CLOUDRON_MONGODB_URL
- CLOUDRON_LOCAL_AUTH_FILE
- and all variables beginning with LDAP\_ are now CLOUDRON\_LDAP\_…

It took me an hour of being quite confused, then opening the source code to see the issue.

**Comment by nebulade** [comment]
Thanks for reporting and sorry that I didn't update the readme.
