### ISSUE TITLE
ability to add Pictures from clipboard 

### ISSUE THREAD

**Issue by Benchwork** [nebulade/meemo#34]
the Idea would be, to be able to add Pictures directly from the clipboard.
a lot of times I just snip/grab an image or screenshot and would like to be able to paste it.

could this be done by adding the image as a data blob? or have it upload like Github just did with this?

`![image](https://cloud.githubusercontent.com/assets/7304823/20577010/60d2c0fc-b18e-11e6-97a3-2ab93d43c21a.png)`

you can just paste it in and it will upload it and assign it a name and all. 

thanks

**Comment by nebulade** [comment]
Hi, that's a great idea. I haven't done any copy'n'paste of data into the browser yet. Have to see how that works.

**Comment by Benchwork** [comment]
might be able to use this as a baseline https://github.com/JoelBesada/pasteboard
