### ISSUE TITLE
Unable to extract username from

### ISSUE THREAD

**Issue by foorb** [nebulade/meemo#43]
Hi,
I enabled email receiving, but getting the following error
```
Email receiving is enabled
ERROR Unable to extract username from user@domain.tld [ /home/user/guacamoly/src/mail.js:175:33 ]
```

**Comment by nebulade** [comment]
That is never tested outside a Cloudron installation. The username extraction works based on the extraction of `appmailboxname+username@domain.tld` where at least in the Cloudron case, the app mailboxname is for example `notes`, which would result in an email address of `notes+username@domain.tld`

I guess the detection can be done smarter, what is the address layout in your case?

**Comment by foorb** [comment]
address layout is simply user@domain.tld
