### ISSUE TITLE
can someone fix the table view? 

### ISSUE THREAD

**Issue by huggenknubbel** [nebulade/meemo#55]
the table view is horrible. can someone fix the css? 
[example](http://note.knubbel.me/shared.html?userId=huggenknubbel&id=5869420dca42c606d81a4997)

**Comment by nebulade** [comment]
Indeed, I haven't put any styling for the table in the stylesheet.

Do you have any suggestions for a clean style?

**Comment by huggenknubbel** [comment]
mabe like [there](
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

2017-01-01 21:19 GMT+01:00 Johannes Zellner <notifications@github.com>:

**Comment by huggenknubbel** [comment]
mabe like [there](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

**Comment by nebulade** [comment]
Looks good, if you like to get it sooner than I get around to fix it, please submit a pull request or I can quickly add it if I have a clean copy of the css for it to look like that.

**Comment by nebulade** [comment]
The examples at https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables should render nicely now
