### ISSUE TITLE
Use ctrl+f to give the search focus

### ISSUE THREAD

**Issue by nebulade** [nebulade/meemo#58]

**Comment by mohsentaleb** [comment]
IMHO as a UI/UX guy, hijacking default browser behavior is a bad practice. especially when it comes to Ctrl+f. Consider you have already searched for a tag/word, and it returns a bunch of notes for the result, which all have the word. Then you need the default browser functionality for searching through the texts, desperately looking for the one you need between all these results, you press ctrl+f and bam, it again takes your cursor to app's search bar. This doesn't work.
