### ISSUE TITLE
Archive function

### ISSUE THREAD

**Issue by little-curiosity** [nebulade/meemo#61]
Hi,

would it be possible to have an archive function? The archived notes will be hidden from the list but can still be searched through tags or some kind of labels, folders? I have many notes that I want to keep but do not want to have a long and messy note list.

Thank you,

little-curiosity

**Comment by nebulade** [comment]
I was thinking of adding some kind of "done" state to notes, which is especially useful for todo lists. I think this ends up being then the same as archive.
Don't know yet when I get around to add this, but I eventually will.

**Comment by nebulade** [comment]
This is now fixed. There might be some caveats when searching with tags still.
