### ISSUE TITLE
URL Prefix

### ISSUE THREAD

**Issue by jkleininger** [nebulade/meemo#69]
I'm having trouble hosting meemo in a reverse proxy folder.  Doing this on a subdomain is easy, and maybe I'm just not enough of an nginx expert, but -- Is there an environment variable to specify a url prefix to enable simple hosting in reverse-proxied folder?

e.g. URL_PREFIX=meemo  -->  http://mydomain.com/meemo

**Comment by nebulade** [comment]
Hm that was indeed never tested as the main deployment target is https://cloudron.io where it is served on subdomains.

I guess this would require changes in the html files and `core.js` to simply use relative paths instead of `/` ?

**Comment by nebulade** [comment]
I have no intention to add this. Subdomains are easy to setup and the routing of subdomains can also be easily done in a reverse proxy like nginx.
