### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by jamietanna** [nebulade/meemo#70]
Is there any expected timeline for offline support / a mobile app? Meemo looks really nice, but having support for mobile devices is going to stop me from immediately switching over

**Comment by nebulade** [comment]
Due to the lack of android or ios experience on my side, this is unlikely to happen unless someone else with interest tackles mobile apps.

**Comment by enrico-kaack** [comment]
Meemo is exactly what I was looking for, great project! I try to transform the web app into an offline first, progressive web app using a service worker and the browsers indexedDB. I will open a pull request when it is usable and tested.

**Comment by nebulade** [comment]
Will close this, as it is out of scope for me. Anyways if @enrico-kaack manages to pull of an indexedDB version it will come up as a pull request again.

**Comment by jamietanna** [comment]
Can we maybe leave this issue open, so then people can see it's a wanted feature? Hopefully they'll be able to contribute something to provide this functionality.
