### ISSUE TITLE
[WIKI] Api Doc 

### ISSUE THREAD

**Issue by vabene1111** [nebulade/meemo#73]
since i wanted to build a simple android client, i analysed the API and wrote down everything i needed for now.

To potentially save someone some work here you go:
> This is not complete and probably has some typos, ..
> If you want you can put it into the wiki, sadly GitHub does not allow PR's to wiki pages

---

# Meemo API Docs

The API can be found under `meemourl/api/<api-name>`

Request Data (POST/PUT) must be send as type `application/json` in a raw body

## Errors

For most API's the following message structure will be returned on Error

```json
{
    "status": "<Error Status e.g. Internal Server Error>",
    "message": "<mesage>"
}
```

## Auth

> It seems that tokens are not automatically invalidated, it is recommended to invalidate (logout) every token after using it.

Type: **POST** `api/login`

Post Body:

```json
{"username":"<username>","password":"<password>"}
```

Response:

```json
{
    "token": "1c828f67-c123-4417-9153-d3847b8919c7",
    "user": {
        "id": "<id>",
        "username": "<username>",
        "displayName": "<displayname>"
    }
}
```

------

Type **GET** `api/logout?token=<token>`

> Invalidates token

Response:

Error or `{}` on success

## Things

Type **GET** `api/things?token=<token>`

Response:

```JSON
{
    "things": [
        {
            "_id": "5947d9d580b52041830d1b1b",
            "content": "Note 2",
            "createdAt": 1497881045925,
            "modifiedAt": 1497881045925,
            "tags": [],
            "externalContent": [],
            "attachments": [],
            "public": false,
            "shared": false,
            "archived": false,
            "richContent": "Note 2"
        },
        {
            "_id": "5947c82280b52041830d1b15",
            "content": "Note 1",
            "createdAt": 1497876514858,
            "modifiedAt": 1497881041669,
            "tags": [],
            "externalContent": [],
            "attachments": [],
            "public": true,
            "shared": false,
            "archived": false,
            "richContent": "Note 1"
        }
    ]
}
```

------

Type **POST** `api/things?token=<token>`

Post Body:

```json
{
        "content": "Note 5",
        "attachments": []
}
```

Response:

```JSON
{
    "thing": {
        "_id": "5947e24d80b52041830d1b1d",
        "content": "Note 5",
        "createdAt": 1497883213258,
        "modifiedAt": 1497883213258,
        "tags": [],
        "externalContent": [],
        "attachments": [],
        "public": false,
        "shared": false,
        "archived": false,
        "richContent": "Note 5"
    }
}
```

------

Type **GET** `api/things/<note id>?token=<token>`

> note id = _id from /api/things

Response:

```json
{
    "thing": {
        "_id": "5947d9d580b52041830d1b1b",
        "content": "Note 2",
        "createdAt": 1497881045925,
        "modifiedAt": 1497881045925,
        "tags": [],
        "externalContent": [],
        "attachments": [],
        "public": false,
        "shared": false,
        "archived": false,
        "richContent": "Note 2"
    }
}
```

------

Type **DELETE** `api/<note id>?<token>`

Response:

```JSOn
{}
```

> Deletes Note by ID

------

Type **PUT** `api/<note id>?<token>`

PUT Body:

```JSON
{
        "content": "Note 1",
        "attachments": [],
        "public": true,
        "shared": false,
        "archived": false
}
```

Response:

```JSOn
{
    "thing": {
        "_id": "5947c82280b52041830d1b15",
        "content": "Note 1",
        "createdAt": 1497876514858,
        "modifiedAt": 1497882953648,
        "tags": [],
        "externalContent": [],
        "attachments": [],
        "public": true,
        "shared": false,
        "archived": false,
        "richContent": "Note 1"
    }
}
```

> Updates Note by ID, returns Updated Note or Error

**Comment by nebulade** [comment]
Thanks a lot! I have updated the API docs to reflect the `sticky` property and put it into the wiki now. Feel free to edit the wiki page if possible to improve on that. The page is at https://github.com/nebulade/meemo/wiki/Rest-API-Docs
