### ISSUE TITLE
LDAP Auth Error

### ISSUE THREAD

**Issue by Frankstar** [nebulade/meemo#75]
Node Version: v6.11.3

Im Starting meemo - no errors.
I try to logon the following Error is showing:

`LdapErr: DSID-0C090748, comment: In order to perform this operation a successful bind must be completed on the connection.`

My Bindings should be fine.

full log see attechment.
I searched the net for a possible solution but couldnt find one.
some had this error with old nodejs version.

[meemo.txt](https://github.com/nebulade/meemo/files/1360143/meemo.txt)

Update:
oh i forgot im using MS-AD.
posting my Config:

```
LDAP_BIND_DN=CN="ldapconnect,CN=Users,DC=domain,DC=local"
LDAP_BIND_PASSWORD="password"
LDAP_USERS_BASE_DN="OU=users,OU=someou,DC=domain,DC=local"
LDAP_URL="ldap://10.0.0.20:389"
```

**Comment by nebulade** [comment]
Is the wrong position of the quotes in the `LDAP_BIND_DN` just a copy and paste error, or actually like this in the configs?

**Comment by Frankstar** [comment]
actually its a typo just here.
im using a systemd Service to start it.
so it looks like this:

```
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
Environment=APP_ORIGIN=http://note.franzholzer.com
Environment=NODE_PORT=3002
Environment=LDAP_BIND_DN=CN=ldapconnect,CN=Users,DC=domain,DC=local
Environment=LDAP_BIND_PASSWORD=password
Environment=LDAP_USERS_BASE_DN=OU=users,OU=someou,DC=domain,DC=local
Environment=LDAP_URL=ldap://10.0.0.20:389
```

without quotes at all.
but i tryed to not "confuse" you - since im not sure if you are familiar with systemd.
(it doesnt work with the quotes)

right now im using a local user (no LDAP) - and using this

`Environment=LOCAL_AUTH_FILE=.users.json`

**Comment by nebulade** [comment]
Thanks for responding quickly. Seems like there is an actual bug, where there is no bind happening in that code path.

**Comment by nebulade** [comment]
I pushed a possible fix to master, although not tested at all. Can you give it a quick try?

**Comment by Frankstar** [comment]
The error is gone!

But got a new one tho

```
node[26365]: at EventEmitter.<anonymous> (/opt/nodejsapps/meemo/src/users.js:99:61)
node[26365]: at emitOne (events.js:96:13)
node[26365]: at EventEmitter.emit (events.js:188:7)
node[26365]: at sendResult (/opt/nodejsapps/meemo/node_modules/ldapjs/lib/client/client.js:1389:22)
node[26365]: at messageCallback (/opt/nodejsapps/meemo/node_modules/ldapjs/lib/client/client.js:1421:16)
node[26365]: at Parser.onMessage (/opt/nodejsapps/meemo/node_modules/ldapjs/lib/client/client.js:1089:14)
node[26365]: at emitOne (events.js:96:13)
node[26365]: at Parser.emit (events.js:188:7)
node[26365]: at Parser.write (/opt/nodejsapps/meemo/node_modules/ldapjs/lib/messages/parser.js:117:8)
node[26365]: at Socket.onData (/opt/nodejsapps/meemo/node_modules/ldapjs/lib/client/client.js:1076:22)
node[26365]: """
node[26365]: code:    internal error
```

not sure about that.
I even delete the `.user.json` and of course removed the `Environment=LOCAL_AUTH_FILE=.users.json`
should i raise a new issue?

**Comment by Frankstar** [comment]
update: published full error.

**Comment by nebulade** [comment]
Yes, please do, that seems like a different issue.
