### ISSUE TITLE
Support of https

### ISSUE THREAD

**Issue by Que20** [nebulade/meemo#81]
Would you consider it ? Might be a good enhancement for you app.
(great app, btw, I use it a lot on my!)

**Comment by Frankstar** [comment]
i use it with https (via haproxy / SSL-Termination)

**Comment by Que20** [comment]
🤔
I might have messed up with my nginx configuration...

**Comment by Frankstar** [comment]
well, you also can use nginx for that, sure

**Comment by Que20** [comment]
My nginx config file seem ok. May be linked to the fact that I'm not using cloudron ?
`
upstream meemo.myDomain {
    server localhost:3000;
}

server {
   listen 443;
   server_tokens off;
   ssl on;
   ssl_certificate /etc/nginx/ssl/server.cer;
   ssl_certificate_key /etc/nginx/ssl/server.key;
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED;
   server_name meemo.myDomain.com;
    location / {
        proxy_pass https://meemo.myDomain;
    }
    location /websocket/ {
        proxy_pass https://meemo.myDomain;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
`

**Comment by Frankstar** [comment]
first - im not fimiliar with nginx.
second - not a meemo or cloudron problem - i dont using cloudron either.
third - i think your `proxy_pass` is wrong

why would you redirect 443 to 443 ?
Thats not the point of SSL Termination.

shouldnt it redirect to something like `proxy_pass http://localhost:3000/`
where your "non https instance of meemo" is running ?

**Comment by Que20** [comment]
My bad! You are right. Sorry, closing the issue now. Thanks!
