### ISSUE TITLE
Endless requests

### ISSUE THREAD

**Issue by foorb** [nebulade/meemo#85]
Hi, when i scroll to the bottom/last note, meemo will stuck in a loop and makes endless reqeusts:

![bildschirmfoto 2018-07-20 um 10 10 41](https://user-images.githubusercontent.com/14993807/42991220-3fa37090-8c05-11e8-8629-77d8bab2c2e6.png)

regards,
foo

**Comment by nebulade** [comment]
This is due to the auto fetching when the page is scrolled all the way to the bottom. Maybe there is a bug with the viewport height changing. Is this on all browsers for you or just chrome (assuming by the screenshot)?

**Comment by foorb** [comment]
Hi, seems to be on chrome only. I can't reproduce it with firefox or safari.

**Comment by nebulade** [comment]
Thanks for narrowing this down, I will try to reproduce this in chrome then
