### ISSUE TITLE
Firefox extension: Add selected text

### ISSUE THREAD

**Issue by sprnza** [nebulade/meemo#87]
It would be great to get FF extension adding selected text (and possibly images) prepent to an URL when a note is being created.

**Comment by nebulade** [comment]
This actually seems like a really good feature. @sprnza do you have any ideas how to get this within an extension context?

**Comment by sprnza** [comment]
Nope, unfortunately.

**Comment by nebulade** [comment]
So the firefox extension is updated with that feature now and published to the extension library. So everyone should get an update automatically at some point. 
Regarding chrome, I simply cannot figure out how to update that in the chrome web store and I didn't find a way to get in touch with google support on this matter.
