### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [nebulade/meemo#89]
Hi, I'm a logo designer, I saw your project and I can make a free logo for your project. So, what do you think?

**Comment by nebulade** [comment]
Hi. Well sure that would be great, the current one is just a random pick really. I cannot promise to use it though before I've seen it though :-)

**Comment by tebriz159** [comment]
Hi again, I made a logo, if you like it I will send you all files to use it. 
 ![meemoltpr2](https://user-images.githubusercontent.com/31902754/52526438-840cce80-2c6d-11e9-831b-30c172c86115.png)

I've made some color variations of the logo, which color and logotype variation do you want?

![meemoltpr](https://user-images.githubusercontent.com/31902754/52526470-f1206400-2c6d-11e9-91d1-d778c50f5354.png)

**Comment by tebriz159** [comment]
Hi again, I made a logo. If you like it I'll send you all files to use it.
![meemoltpr2](https://user-images.githubusercontent.com/31902754/52532398-6a08d580-2cd9-11e9-951e-c24d598fcaba.png)

I've made some color variations of the logo, which color and logotype variation do you prefer?

![meemoltpr](https://user-images.githubusercontent.com/31902754/52532404-84db4a00-2cd9-11e9-9e57-91827341abf6.png)

**Comment by nebulade** [comment]
Thanks, they look great. I think I will go with the purple to blue one. Is it possible to get also the files as svg? I would have to extract the magnifier glass alone also for the the favicon.

**Comment by tebriz159** [comment]
Sure, all files is here: https://drive.google.com/open?id=17_tK0stcuASwJVa-9uDAU7T1sdkL9Lts
Please LMK when you use it.

**Comment by nebulade** [comment]
@tebriz159 how do you want to be mentioned in the app for the contribution? So far there were practically no contributions, so there is nothing setup yet
