### ISSUE TITLE
Meemo creates an invalid email (on cloudron)

### ISSUE THREAD

**Issue by necrevistonnezr** [nebulade/meemo#92]
I just installed Meemo through the Cloudron appstore.
Meemo created the following (invalid) address to receive mails (domain and username masked): meemo.app@mydomain.com+username@mydomain.com

**Comment by gramakri** [comment]
This seems like a display issue.

Changing https://github.com/nebulade/meemo/blob/master/src/routes.js#L140 to `process.env.MAIL_IMAP_USERNAME.split('@')[0]` makes it show correctly.

**Comment by gramakri** [comment]
Email feature itself works fine (have to create mailbox manually with the latest cloudron release).

**Comment by nebulade** [comment]
Thanks @gramakri for fixing this with 654661d8274a89a63ef808b7b84a7e04d3175014
